import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';

// `./managed/feedback` is generated by `npm run compact`. Until you have run
// the Compact compiler once, this import will not resolve — that is expected,
// and it is why `npm run compact` comes before `npm run build`.
export * from './managed/feedback/contract/index.js';
export * from './witnesses.js';

import * as CompiledFeedbackContract from './managed/feedback/contract/index.js';
import * as Witnesses from './witnesses.js';

/**
 * The compiled Anonymous Feedback Board contract, bound to its witness
 * implementations and its generated ZK key material. This is the object the
 * API layer hands to `deployContract` / `findDeployedContract`.
 */
export const CompiledFeedbackBoardContract = CompiledContract.make<
  CompiledFeedbackContract.Contract<Witnesses.FeedbackPrivateState>
>('FeedbackBoard', CompiledFeedbackContract.Contract<Witnesses.FeedbackPrivateState>).pipe(
  CompiledContract.withWitnesses(Witnesses.witnesses),
  CompiledContract.withCompiledFileAssets('./managed/feedback'),
);
